export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_ALL_PROJECTS_START = 'GET_ALL_PROJECTS_START'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'
export const GET_ALL_PROJECTS_ERROR = 'GET_ALL_PROJECTS_ERROR'

export const GET_ALL_PROJECTS_TASK_START = 'GET_ALL_PROJECTS_TASK_START'
export const GET_ALL_PROJECTS_TASK_SUCCESS = 'GET_ALL_PROJECTS_TASK_SUCCESS'
export const GET_ALL_PROJECTS_TASK_ERROR = 'GET_ALL_PROJECTS_TASK_ERROR'

export const CLEAR_ALL_TASKS = 'CLEAR_ALL_TASKS'

export const AUTH_USER_LOADING = 'AUTH_USER_LOADING'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'

export const ADD_PROJECT_LOG_START = 'ADD_PROJECT_LOG_START'
export const ADD_PROJECT_LOG_SUCCESS = 'ADD_PROJECT_LOG_SUCCESS'
export const ADD_PROJECT_LOG_ERROR = 'ADD_PROJECT_LOG_ERROR'

export const UPDATE_PROJECT_LOG_START = 'UPDATE_PROJECT_LOG_START'
export const UPDATE_PROJECT_LOG_SUCCESS = 'UPDATE_PROJECT_LOG_SUCCESS'
export const UPDATE_PROJECT_LOG_ERROR = 'UPDATE_PROJECT_LOG_ERROR'

export const GET_LOGS_BY_PROJECT_ID_START = 'GET_LOGS_BY_PROJECT_ID_START'
export const GET_LOGS_BY_PROJECT_ID_SUCCESS = 'GET_LOGS_BY_PROJECT_ID_SUCCESS'
export const GET_LOGS_BY_PROJECT_ID_ERROR = 'GET_LOGS_BY_PROJECT_ID_ERROR'

export const GET_LOGS_BY_TASK_ID_START = 'GET_LOGS_BY_TASK_ID_START'
export const GET_LOGS_BY_TASK_ID_SUCCESS = 'GET_LOGS_BY_TASK_ID_SUCCESS'
export const GET_LOGS_BY_TASK_ID_ERROR = 'GET_LOGS_BY_TASK_ID_ERROR'

export const GET_LOGS_BY_VIEW_START = 'GET_LOGS_BY_VIEW_START'
export const GET_LOGS_BY_VIEW_SUCCESS = 'GET_LOGS_BY_VIEW_SUCCESS'
export const GET_LOGS_BY_VIEW_ERROR = 'GET_LOGS_BY_VIEW_ERROR'

export const UPDATE_LOGS_STATUS = 'UPDATE_LOGS_STATUS'